### ISSUE TITLE
Getting No ViewManager defined for class RNLinearTextGradient

### ISSUE THREAD

**Issue by Hodor9898** [iyegoroff/react-native-text-gradient#13]
"react-native-text-gradient": "0.0.13",
    "react-native": "~0.55.2",

I ran `rnpm link  react-native-text-gradient`

```
npm-link info Android module react-native-text-gradient is already linked
rnpm-link info iOS module react-native-text-gradient is already linked
rnpm-link info Linking assets to ios project
rnpm-link info Linking assets to android project
rnpm-link info Assets has been successfully linked to your project
```

How can i fix this issue?

**Comment by iyegoroff** [comment]
1. You need to use rntg 0.0.9 - https://github.com/iyegoroff/react-native-text-gradient#status
2. Use `react-native link` instead of `rnpm link`.

**Comment by Hodor9898** [comment]
First of all, thanks for the quick response :) but i tried your suggestion and it still says the same,

i ran: 

1. yarn remove react-native-text-gradient
2. react-native unlink react-native-text-gradiant
3. yarn add react-native-text-gradient
4. react-native link

but im still getting the same response :(

**Comment by Hodor9898** [comment]
Im getting this error when trying to run npm start on the TextGradientExample

```
C:\Users\Admin\WebstormProjects\react-native-text-gradient\TextGradientExample\node_modules\react-native\local-cli\cliEntry.js:30
import type {CommandT} from './commands';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (C:\Users\Admin\WebstormProjects\react-native-text-gradient\TextGradientExample\node_modules\pirates\lib\index.js:91:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (C:\Users\Admin\WebstormProjects\react-native-text-gradient\TextGradientExample\node_modules\pirates\lib\index.js:96:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

**Comment by Hodor9898** [comment]
Still not working, why did you close this issue?
