### ISSUE TITLE
android apk release error

### ISSUE THREAD

**Issue by taohaibing** [iyegoroff/react-native-text-gradient#34]
09-17 11:46:55.448 20714 20714 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at iyegoroff.RNTextGradient.k.a()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at iyegoroff.RNTextGradient.h.j()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at iyegoroff.RNTextGradient.h.a()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at iyegoroff.RNTextGradient.g.a()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.facebook.react.uimanager.da$p.execute()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.facebook.react.uimanager.ba.run()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.facebook.react.uimanager.da.i()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.facebook.react.uimanager.da.i()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.facebook.react.uimanager.da$f.b()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.facebook.react.uimanager.c.a()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.facebook.react.modules.core.i$b.a()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.facebook.react.modules.core.a.doFrame()
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:924)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:735)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:664)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:761)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:156)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6517)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
09-17 11:46:55.448 20714 20714 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by iyegoroff** [comment]
Please specify your rn & rntg versions.

**Comment by taohaibing** [comment]
> Please specify your rn & rntg versions.

react-native-cli: 2.0.1
react-native: 0.60.3

**Comment by iyegoroff** [comment]
This looks ok to me. Can you provide a replicating example or show the code that leads to this error?

**Comment by JDJBSPL** [comment]
Please provide proguard lines, which will work for release builds.

**Comment by JDJBSPL** [comment]
> Please provide proguard lines, which will work for release builds.

Used https://github.com/react-native-community/react-native-masked-view library which is now officially supported for android too. 
Dependent library is react-native-linear-gradient.
