### ISSUE TITLE
ArithmeticException: divide by zero exception on Android

### ISSUE THREAD

**Issue by ionut-movila** [iyegoroff/react-native-text-gradient#8]
I'm using this library and we got this error from a production build.

Not sure what to look for so I'm just printing here the stack trace. Device is LG K20 V, running android 7.0

`
Caused by: java.lang.ArithmeticException: divide by zero
    at iyegoroff.RNTextGradient.Linear.RNLinearTextGradientSpan.isMultiline(RNLinearTextGradientSpan.java:109)
    at iyegoroff.RNTextGradient.Linear.RNLinearTextGradientSpan.updateDrawState(RNLinearTextGradientSpan.java:80)
    at android.text.TextLine.handleRun(TextLine.java:957)
    at android.text.TextLine.measureRun(TextLine.java:395)
    at android.text.TextLine.measure(TextLine.java:285)
    at android.text.TextLine.metrics(TextLine.java:259)
    at android.text.BoringLayout.isBoring(BoringLayout.java:310)
    at android.text.BoringLayout.isBoring(BoringLayout.java:220)
    at com.facebook.react.views.text.ReactTextShadowNode$1.measure(ReactTextShadowNode.java:61)
    at com.facebook.yoga.YogaNode.measure(YogaNode.java:654)
    at com.facebook.yoga.YogaNode.jni_YGNodeCalculateLayout(YogaNode.java:-2)
    at com.facebook.yoga.YogaNode.calculateLayout(YogaNode.java:198)
    at com.facebook.react.uimanager.ReactShadowNodeImpl.calculateLayout(ReactShadowNodeImpl.java:512)
    at com.facebook.react.uimanager.UIImplementation.calculateRootLayout(UIImplementation.java:942)
    at com.facebook.react.uimanager.UIImplementation.updateViewHierarchy(UIImplementation.java:694)
    at com.facebook.react.uimanager.UIImplementation.dispatchViewUpdates(UIImplementation.java:654)
    at com.facebook.react.uimanager.UIManagerModule.updateRootLayoutSpecs(UIManagerModule.java:754)
    at com.facebook.react.ReactRootView$1.runGuarded(ReactRootView.java:396)
    at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:154)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
    at java.lang.Thread.run(Thread.java:761)
`

**Comment by iyegoroff** [comment]
Can you share react-native, react-native-text-gradient versions and js code that leads to this error?

**Comment by iyegoroff** [comment]
It looks like you got this error, because width of LinearTextGradient was set to 0. This should be fixed in 0.0.9.
